services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:securepassword@mongo:27017/flasktest?authSource=admin

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword # Dev password, do not use in production
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: